### ISSUE TITLE
低版本delphi支持？

### ISSUE THREAD

**Issue by edwinyzh** [zhaoyipeng/XDMessaging.Delphi#1]
您好，今天发现这个跨进程通讯项目，非常有用！

请问有考虑支持低版本的Delphi，比如xe4吗？谢谢！

**Comment by zhaoyipeng** [comment]
目前的版本使用了JSON序列化功能，XE4是否能够支持这个功能我不太确定

**Comment by zhaoyipeng** [comment]
已添加低版本支持，目前测试了XE4,XE8,10 Seattle, 10.1 Berlin, 10.2 Tokyo
tested on XE4,XE8,10 Seattle, 10.1 Berlin, 10.2 Tokyo, I think XE5-XE7 is also no problem

**Comment by edwinyzh** [comment]
XE4编译和允许通过，非常感谢！

Thank you @zhaoyipeng  for adding support for Delphi XE4, I've successfully compiled the demo program and get it up running! 

Notes for others worth knowing - The JSON serialization part has replaced with [x-superobject](https://github.com/onryldz/x-superobject) for lower versions of Delphi compiler.
